; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = server

[env:indicator]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = 
	+<indicator/*>
	-<server/*>
extra_scripts = pre:scripts/select_port.py
monitor_speed = 115200
monitor_filters = time
monitor_port = ${sysenv.PIO_MONITOR_PORT}
lib_deps = madhephaestus/ESP32Servo@^3.1.3

[env:server]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = 
	+<server/*>
	-<indicator/*>
extra_scripts = pre:scripts/select_port.py
monitor_speed = 115200
monitor_filters = time
monitor_port = ${sysenv.PIO_MONITOR_PORT}
lib_deps = 
	madhephaestus/ESP32Servo@^3.1.3,


[env:experiment]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DEXPERIMENT_FOLDER=ultrasonic
build_src_filter = 
	+<../experiments/${EXPERIMENT_FOLDER}/*>
	-<*>
extra_scripts = pre:scripts/select_port.py
monitor_speed = 115200
custom_location = 1-9.3
monitor_port = ${sysenv.PIO_MONITOR_PORT}
lib_deps = 
	madhephaestus/ESP32Servo@^3.1.3
